#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Deploy the Enterprise Agentic RAG Azure foundation.

.DESCRIPTION
    Provisions all Day 2 Azure resources via Bicep:
      - User-assigned Managed Identity
      - Key Vault (RBAC model)
      - Storage Account (AI Foundry Hub dependency)
      - Azure OpenAI (GPT-4o + text-embedding-3-large)
      - Azure AI Search (Standard, semantic ranking)
      - Azure AI Foundry Hub + Project

    Resources are deployed to a resource group tagged for the environment.
    Outputs are written to a local .env file (gitignored) for dev use.

.PARAMETER Environment
    Target environment: dev | staging | prod  (default: dev)

.PARAMETER Location
    Azure region (default: eastus).  Must support Azure OpenAI GPT-4o.

.PARAMETER ResourceGroup
    Resource group name (created if not exists). Defaults to rg-erag-<env>.

.PARAMETER SubscriptionId
    Azure subscription ID. Defaults to the current az CLI default subscription.

.EXAMPLE
    .\deploy.ps1 -Environment dev -Location eastus
#>
param(
    [ValidateSet('dev', 'staging', 'prod')]
    [string] $Environment = 'dev',

    [string] $Location = 'eastus',

    [string] $ResourceGroup = "rg-erag-$Environment",

    [ValidateLength(1, 8)]
    [string] $ProjectPrefix = 'erag',

    [string] $SubscriptionId = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Prerequisites check ───────────────────────────────────────────────────────
if (-not (Get-Command 'az' -ErrorAction SilentlyContinue)) {
    Write-Error "'az' is not installed or not on PATH."
}

az bicep version *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Host "Bicep is not available via Azure CLI. Installing it now..." -ForegroundColor Yellow
    az bicep install
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Azure CLI Bicep support is unavailable. Run 'az bicep install' and try again."
    }
}

# ── Subscription ──────────────────────────────────────────────────────────────
if ($SubscriptionId) {
    az account set --subscription $SubscriptionId
}
$sub = (az account show --query id -o tsv).Trim()
Write-Host "Deploying to subscription: $sub" -ForegroundColor Cyan

# ── Deployer principal ID for Key Vault role assignment ───────────────────────
$deployerPrincipalId = (az ad signed-in-user show --query id -o tsv 2>$null).Trim()
if (-not $deployerPrincipalId) {
    Write-Warning "Could not determine signed-in user. Key Vault Secrets Officer role will not be assigned to deployer."
    $deployerPrincipalId = ''
}

# ── Resource group ────────────────────────────────────────────────────────────
Write-Host "Ensuring resource group '$ResourceGroup' in '$Location'..." -ForegroundColor Cyan
az group create --name $ResourceGroup --location $Location --tags environment=$Environment project=enterprise-rag | Out-Null

# ── Bicep deployment ──────────────────────────────────────────────────────────
$deploymentName = "erag-day2-$(Get-Date -Format 'yyyyMMdd-HHmm')"
$bicepFile = Join-Path $PSScriptRoot 'main.bicep'

Write-Host "Starting deployment '$deploymentName'..." -ForegroundColor Cyan
Write-Host "Using project prefix '$ProjectPrefix'" -ForegroundColor Cyan

$result = az deployment group create `
    --name $deploymentName `
    --resource-group $ResourceGroup `
    --template-file $bicepFile `
    --parameters environment=$Environment location=$Location projectPrefix=$ProjectPrefix deployerPrincipalId=$deployerPrincipalId `
    --output json | ConvertFrom-Json

if ($LASTEXITCODE -ne 0) {
    Write-Error "Deployment failed. Check the Azure portal for details."
}

$outputs = $result.properties.outputs

Write-Host "`nDeployment succeeded!" -ForegroundColor Green
Write-Host "──────────────────────────────────────────────────────" -ForegroundColor Green

# ── Write .env file (gitignored, for local dev) ───────────────────────────────
$envFile = Join-Path (Split-Path $PSScriptRoot -Parent) '.env'

$envContent = @"
# Auto-generated by infra/deploy.ps1 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# DO NOT COMMIT — this file is gitignored.

AZURE_CLIENT_ID=$($outputs.managedIdentityClientId.value)
AZURE_KEYVAULT_URL=$($outputs.keyVaultUri.value)
AZURE_OPENAI_ENDPOINT=$($outputs.openAiEndpoint.value)
AZURE_OPENAI_CHAT_DEPLOYMENT=$($outputs.chatDeploymentName.value)
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=$($outputs.embeddingDeploymentName.value)
AZURE_SEARCH_ENDPOINT=$($outputs.searchEndpoint.value)
AZURE_SEARCH_INDEX_NAME=rag-index
AZURE_AI_FOUNDRY_PROJECT_CONNECTION_STRING=$($outputs.aiFoundryProjectConnectionString.value)
"@

Set-Content -Path $envFile -Value $envContent -Encoding utf8
Write-Host ".env written to: $envFile" -ForegroundColor Yellow
Write-Host "(Add AZURE_SUBSCRIPTION_ID and AZURE_RESOURCE_GROUP if needed by SDKs)" -ForegroundColor Yellow
