"""Shared cost model for Azure OpenAI and Azure AI Search.

Provides bounded cost estimates for a single RAG request and projected
monthly costs.  Prices are approximations based on Azure public pricing
and should be updated when actual deployments are confirmed.

Usage::

    from cost_model.estimator import CostEstimator, RequestProfile

    estimator = CostEstimator()
    estimate = estimator.estimate_request(
        RequestProfile(
            input_tokens=800,
            output_tokens=400,
            embedding_tokens=512,
            search_queries=2,
        )
    )
    print(estimate.total_usd)          # Decimal('0.00...')
    print(estimate.formatted_summary)  # human-readable breakdown
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal

# ── Price tables ──────────────────────────────────────────────────────────────
# All prices are USD per million tokens (or per 1 000 queries for Search).
# Source: Azure public pricing pages (approximate, region: East US, 2024).
# Update these constants when actual deployment pricing is confirmed.

_GPT4O_INPUT_PER_1M = Decimal("5.00")      # GPT-4o input tokens
_GPT4O_OUTPUT_PER_1M = Decimal("15.00")    # GPT-4o output tokens
_EMBEDDING_PER_1M = Decimal("0.13")        # text-embedding-3-large
_SEARCH_PER_1K_QUERIES = Decimal("0.001")  # AI Search S1, per 1 000 queries


@dataclass(frozen=True)
class RequestProfile:
    """Describes the token and query usage of a single RAG request."""

    input_tokens: int = 0        # tokens sent to GPT-4o (system + context + user)
    output_tokens: int = 0       # tokens generated by GPT-4o
    embedding_tokens: int = 0    # tokens sent to the embedding model (query embed)
    search_queries: int = 1      # number of AI Search queries (vector + keyword)


@dataclass(frozen=True)
class CostBreakdown:
    """Cost breakdown by Azure service for a single request."""

    openai_input_usd: Decimal
    openai_output_usd: Decimal
    embedding_usd: Decimal
    search_usd: Decimal

    @property
    def total_usd(self) -> Decimal:
        return (
            self.openai_input_usd
            + self.openai_output_usd
            + self.embedding_usd
            + self.search_usd
        )


@dataclass(frozen=True)
class CostEstimate:
    """Full cost estimate for a single RAG request."""

    profile: RequestProfile
    breakdown: CostBreakdown

    @property
    def total_usd(self) -> Decimal:
        return self.breakdown.total_usd

    @property
    def formatted_summary(self) -> str:
        b = self.breakdown
        lines = [
            "Cost estimate (USD)",
            f"  GPT-4o input  ({self.profile.input_tokens:>7} tokens): ${b.openai_input_usd:.6f}",
            f"  GPT-4o output ({self.profile.output_tokens:>7} tokens): ${b.openai_output_usd:.6f}",
            f"  Embedding     ({self.profile.embedding_tokens:>7} tokens): ${b.embedding_usd:.6f}",
            f"  AI Search     ({self.profile.search_queries:>7} queries): ${b.search_usd:.6f}",
            "  ─────────────────────────────────────────────",
            f"  Total                                        ${b.total_usd:.6f}",
        ]
        return "\n".join(lines)


@dataclass
class MonthlyProjection:
    """Projected monthly cost for a given daily request volume."""

    daily_requests: int
    cost_per_request_usd: Decimal
    days_per_month: int = 30

    @property
    def monthly_usd(self) -> Decimal:
        return (
            self.daily_requests * self.cost_per_request_usd * self.days_per_month
        ).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

    @property
    def formatted_summary(self) -> str:
        return (
            f"Monthly projection: {self.daily_requests} req/day × "
            f"${self.cost_per_request_usd:.6f}/req × {self.days_per_month} days "
            f"= ${self.monthly_usd:.2f}/month"
        )


class CostEstimator:
    """Computes cost estimates for Azure OpenAI + AI Search usage.

    Args:
        gpt4o_input_per_1m: Price per million GPT-4o input tokens (USD).
        gpt4o_output_per_1m: Price per million GPT-4o output tokens (USD).
        embedding_per_1m: Price per million embedding tokens (USD).
        search_per_1k_queries: Price per 1 000 AI Search queries (USD).
    """

    def __init__(
        self,
        gpt4o_input_per_1m: Decimal = _GPT4O_INPUT_PER_1M,
        gpt4o_output_per_1m: Decimal = _GPT4O_OUTPUT_PER_1M,
        embedding_per_1m: Decimal = _EMBEDDING_PER_1M,
        search_per_1k_queries: Decimal = _SEARCH_PER_1K_QUERIES,
    ) -> None:
        self._gpt4o_input = gpt4o_input_per_1m
        self._gpt4o_output = gpt4o_output_per_1m
        self._embedding = embedding_per_1m
        self._search = search_per_1k_queries

    # ── Per-request estimate ─────────────────────────────────────────────────
    def estimate_request(self, profile: RequestProfile) -> CostEstimate:
        """Return a ``CostEstimate`` for a single RAG request."""
        _1m = Decimal("1_000_000")
        _1k = Decimal("1_000")

        breakdown = CostBreakdown(
            openai_input_usd=(Decimal(profile.input_tokens) / _1m * self._gpt4o_input),
            openai_output_usd=(Decimal(profile.output_tokens) / _1m * self._gpt4o_output),
            embedding_usd=(Decimal(profile.embedding_tokens) / _1m * self._embedding),
            search_usd=(Decimal(profile.search_queries) / _1k * self._search),
        )
        return CostEstimate(profile=profile, breakdown=breakdown)

    # ── Monthly projection ────────────────────────────────────────────────────
    def project_monthly(
        self,
        profile: RequestProfile,
        daily_requests: int,
        days_per_month: int = 30,
    ) -> MonthlyProjection:
        """Project monthly cost for a given daily request volume."""
        estimate = self.estimate_request(profile)
        return MonthlyProjection(
            daily_requests=daily_requests,
            cost_per_request_usd=estimate.total_usd,
            days_per_month=days_per_month,
        )

    # ── Bounded-budget check ──────────────────────────────────────────────────
    def is_within_budget(
        self,
        profile: RequestProfile,
        daily_requests: int,
        monthly_budget_usd: Decimal,
        days_per_month: int = 30,
    ) -> bool:
        """Return True if the projected monthly cost is within ``monthly_budget_usd``."""
        projection = self.project_monthly(profile, daily_requests, days_per_month)
        return projection.monthly_usd <= monthly_budget_usd
